<a href="https://colab.research.google.com/github/Quark-hadron/PyTorch_lessons/blob/main/pytorch_lesson_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
! pip install torch;

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 76.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 63.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 43.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 14.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 89.6 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlin

In [ ]:
import torch

In [ ]:
torch.tensor([[1,1], [2,4]], dtype=torch.float32, requires_grad=True)

tensor([[1., 1.],
        [2., 4.]], requires_grad=True)

In [ ]:
tensor_one = torch.tensor([[[12,14],[14,8]],
              [[45,7], [1,7]]],
              dtype=torch.float32, requires_grad=True)

In [ ]:
tensor_one

tensor([[[12., 14.],
         [14.,  8.]],

        [[45.,  7.],
         [ 1.,  7.]]], requires_grad=True)

In [ ]:
tensor_one.shape

torch.Size([2, 2, 2])

In [ ]:
tensor_one.size()

torch.Size([2, 2, 2])

In [ ]:
tensor_one.ndim

3

In [ ]:
tensor_one[0, 1, 1]

tensor(8., grad_fn=<SelectBackward0>)

In [ ]:
type(tensor_one[0, 1, 1])

torch.Tensor

In [ ]:
tensor_one[0, 1, 1].item()

8.0

In [ ]:
type(tensor_one[0, 1, 1].item())

float

In [ ]:
torch.zeros([2, 2, 3], dtype=torch.int8)

tensor([[[0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0]]], dtype=torch.int8)

In [ ]:
torch.ones([3,2,2], dtype=torch.int8)

tensor([[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]], dtype=torch.int8)

In [ ]:
tensor = torch.zeros_like(torch.ones([3,2,2], dtype=torch.int8))
tensor

tensor([[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]], dtype=torch.int8)

In [ ]:
torch.ones_like(tensor)

tensor([[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]], dtype=torch.int8)

In [ ]:
torch.full_like(tensor, 52)

tensor([[[52, 52],
         [52, 52]],

        [[52, 52],
         [52, 52]],

        [[52, 52],
         [52, 52]]], dtype=torch.int8)

In [ ]:
torch.arange(1, 2.1, 0.1)

tensor([1.0000, 1.1000, 1.2000, 1.3000, 1.4000, 1.5000, 1.6000, 1.7000, 1.8000,
        1.9000, 2.0000])

In [ ]:
torch.diag(torch.arange(0,10,1))

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [ ]:
torch.diag(~torch.arange(0,10,1))

tensor([[ -1,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,  -2,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,  -3,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,  -4,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,  -5,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,  -6,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,  -7,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,  -8,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,  -9,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0, -10]])

In [ ]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
torch.tril(torch.tensor([[1,2,3,9], [14,7,8,7], [7,8,9,1], [1,7,6,4]]))

tensor([[ 1,  0,  0,  0],
        [14,  7,  0,  0],
        [ 7,  8,  9,  0],
        [ 1,  7,  6,  4]])

In [ ]:
torch.tril(~torch.tensor([[1,2,3,9], [14,7,8,7], [7,8,9,1], [1,7,6,4]]))

tensor([[ -2,   0,   0,   0],
        [-15,  -8,   0,   0],
        [ -8,  -9, -10,   0],
        [ -2,  -8,  -7,  -5]])

In [ ]:
tensor

tensor([[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]], dtype=torch.int8)

In [ ]:
tensor.reshape([3,4])

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int8)

In [ ]:
tensor = torch.tensor([1,5,61,45])
tensor

tensor([ 1,  5, 61, 45])

In [ ]:
tensor.shape

torch.Size([4])

In [ ]:
tensor = torch.unsqueeze(tensor, 0)
tensor

tensor([[ 1,  5, 61, 45]])

In [ ]:
tensor.shape

torch.Size([1, 4])

In [ ]:
tensor = tensor.squeeze()
tensor

tensor([ 1,  5, 61, 45])

In [ ]:
tensor = tensor * 5
tensor

tensor([  5,  25, 305, 225])

In [ ]:
tensor.sum()

tensor(560)

In [ ]:
torch.Tensor([1,2,36,4]).mean()

tensor(10.7500)

In [ ]:
tensor = torch.tensor([1,2,4,5,8,9], dtype=torch.float32)
tensor

tensor([1., 2., 4., 5., 8., 9.])

In [ ]:
tensor = tensor.reshape([2,3])
tensor

tensor([[1., 2., 4.],
        [5., 8., 9.]])

In [ ]:
tensor_mean = tensor.mean(dim=1)
tensor_mean

tensor([2.3333, 7.3333])

In [ ]:
tensor_mean.size()

torch.Size([2])

In [ ]:
tensor_mean = tensor.mean(dim=1, keepdim=True)
tensor_mean

tensor([[2.3333],
        [7.3333]])

In [ ]:
tensor_mean.size()

torch.Size([2, 1])

* Особености PyTorch

In [ ]:
print(torch.cpu.is_available())

True


In [ ]:
print(torch.cuda.is_available())

True


In [ ]:
tensor = tensor.cuda()
tensor

tensor([[1., 2., 4.],
        [5., 8., 9.]], device='cuda:0')

In [ ]:
tensor = tensor.cpu()
tensor

tensor([[1., 2., 4.],
        [5., 8., 9.]])

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

tensor = tensor.to(device)

tensor

tensor([[1., 2., 4.],
        [5., 8., 9.]], device='cuda:0')

In [ ]:
tensor.device

device(type='cuda', index=0)

In [ ]:
tensor_1 = torch.tensor([1,2,3,4,6,46], dtype=torch.float32, requires_grad=True)

tensor_2 = torch.tensor([7,6,3,64,6,6], dtype=torch.float32, requires_grad=True)

tensor_new = tensor_1 + tensor_2

tensor_new

tensor([ 8.,  8.,  6., 68., 12., 52.], grad_fn=<AddBackward0>)

In [ ]:
tensor_new.detach()

tensor([ 8.,  8.,  6., 68., 12., 52.])